Repository FalkAlexander/traffy, pull requests merged in 2020-10, with the labels that each got.

#5 Rework device unlock
  traffy-server/app/util/ipset_helper.py
  traffy-server/app/util/iptables_rules_manager.py
  traffy-server/server.py
Labels: hacktoberfest-accepted

#8 Adopt nftables
  traffy-server/app/accounting_manager.py
  traffy-server/app/api/server.py
  traffy-server/app/housekeeping_service.py
  traffy-server/app/util/ipset_helper.py
  traffy-server/app/util/iptables_accounting_manager.py
  traffy-server/app/util/iptables_rules_manager.py
  traffy-server/app/util/nftables_manager.py
  traffy-server/config.py.example
  traffy-server/server.py
Labels: performance

#9 Reimplement spoofing protection
  traffy-server/app/api/server.py
  traffy-server/app/util/arp_manager.py
  traffy-server/app/util/nftables_manager.py
  traffy-server/server.py
Labels: enhancement
